forward_speed: 0.75               # Constant forward velocity
constant_forward_speed: False     # Stop when obstacle in safety area (no slowdown)
min_obj_size: 0.15                # Minimum object radius for slow down
min_dist_to_obj: 1.5              # Distance to object at which the robot should stop
approach_dist_to_obj: 4.0         # Distance to object at which the robot starts to slow down
minimum_turning_speed: 0.01       # Minimum turning speed
kp_ang_ro: 0.7                    # Proportional gain for initial orientation target
initial_heading_tolerance: 0.04   # Initial heading tolerance in radians
kp_ang: 0.5                       # Proportional gain for heading correction
kp_y: 0.75                        # Proportional gain for sideways correction
granularity: 0.5                  # Distance between local goals along path (carrots)
y_row_detection_bias: 1.00        # Weight given to the reference given by row detection
y_path_following_bias: 0.15       # Weight given to the original path following
ang_row_detection_bias: 1.06      # Weight given to the angular reference given by row detection
ang_path_following_bias: 0.14     # Weight given to the angular refernce given by path following
emergency_clearance_x: 0.7        # Clearance from corner frames to trigger emergency stop in x
emergency_clearance_y: 0.2        # Clearance from corner frames to trigger emergency stop in y
quit_on_timeout: False            # Wether the robot should cancel row traversal after collision detected
time_to_quit: 10.0                # Time until the action is cancelled since collision detected
goal_tolerance_radius: 0.1        # Goal tolerance Radius in metres
