base_station_nodes: &id_base_stations
  - WayPoint52
  - WayPoint53
wait_nodes: *id_base_stations
local_storage_node: WayPoint54
charging_station_node: WayPoint54
robot_ids: [thorvald_010, thorvald_015]
max_task_priorities: [0, 255]
virtual_pickers: ["picker101", "picker102"]
