rasberry_coordination:
  presence_agents:
    - thorvald_001
    - thorvald_002
    - thorvald_003
    - thorvald_004
    - thorvald_005
    - thorvald_006
    - thorvald_007
    - thorvald_008
    - thorvald_009
    - thorvald_010
    - thorvald_011
    - thorvald_012
    - thorvald_013
    - thorvald_014
    - thorvald_015
    - thorvald_016
    - thorvald_017
    - thorvald_018
    - thorvald_019
    - thorvald_020
    - picker01
    - picker02
    - picker03
    - picker04
    - picker05
    - picker06
    - picker07
    - picker08
    - picker09
    - picker10
    - picker101
    - picker102
    - picker103
    - picker104
    - picker105
    - picker106
    - picker107
    - picker108
    - picker109
    - picker110
