edge_nav_reconfig_groups:
  utn:
    edges:
    - WayPoint48_WayPoint52
    - WayPoint52_WayPoint48
    - WayPoint48_WayPoint53
    - WayPoint53_WayPoint48
    - WayPoint48_WayPoint54
    - WayPoint54_WayPoint48
    - WayPoint48_WayPoint55
    - WayPoint55_WayPoint48
    - WayPoint49_WayPoint52
    - WayPoint52_WayPoint49
    - WayPoint49_WayPoint53
    - WayPoint53_WayPoint49
    - WayPoint49_WayPoint54
    - WayPoint54_WayPoint49
    - WayPoint49_WayPoint55
    - WayPoint55_WayPoint49
    - WayPoint50_WayPoint56
    - WayPoint56_WayPoint50
    - WayPoint50_WayPoint57
    - WayPoint57_WayPoint50
    - WayPoint50_WayPoint58
    - WayPoint58_WayPoint50
    - WayPoint50_WayPoint59
    - WayPoint59_WayPoint50
    - WayPoint51_WayPoint56
    - WayPoint56_WayPoint51
    - WayPoint51_WayPoint57
    - WayPoint57_WayPoint51
    - WayPoint51_WayPoint58
    - WayPoint58_WayPoint51
    - WayPoint51_WayPoint59
    - WayPoint59_WayPoint51
    parameters:
    - name: forward_point_distance
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.1402690117118645
    - name: vth_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 73.0
    - name: prune_plan
      ns: move_base/DWAPlannerROS
      type: bool
      value: false
    - name: goal_distance_bias
      ns: move_base/DWAPlannerROS
      type: int
      value: 55.0
    - name: occdist_scale
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.5922531975286119
    - name: vx_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 50.0
    - name: path_distance_bias
      ns: move_base/DWAPlannerROS
      type: int
      value: 7.0
    - name: sim_time
      ns: move_base/DWAPlannerROS
      type: double
      value: 2.801314735789211
    - name: max_scaling_factor
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.8779488542935023
    - name: scaling_speed
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.31177421746048395
    - name: sim_granularity
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.02537100021859829
    - name: stop_time_buffer
      ns: move_base/DWAPlannerROS
      type: double
      value: 1.0
    - name: oscillation_reset_dist
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.054441156382406555
