edge_nav_reconfig_groups:
  enter_row:
    edges:
    - WayPoint40_WayPoint0
    - WayPoint41_WayPoint10
    - WayPoint42_WayPoint20
    - WayPoint43_WayPoint30
    - WayPoint44_WayPoint9
    - WayPoint45_WayPoint19
    - WayPoint46_WayPoint29
    - WayPoint47_WayPoint39
    parameters: &id001
    - name: forward_point_distance
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.1402690117118645
    - name: vth_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 73.0
    - name: prune_plan
      ns: move_base/DWAPlannerROS
      type: bool
      value: false
    - name: goal_distance_bias
      ns: move_base/DWAPlannerROS
      type: int
      value: 55.0
    - name: occdist_scale
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.5922531975286119
    - name: vx_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 50.0
    - name: path_distance_bias
      ns: move_base/DWAPlannerROS
      type: int
      value: 7.0
    - name: sim_time
      ns: move_base/DWAPlannerROS
      type: double
      value: 2.801314735789211
    - name: max_scaling_factor
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.8779488542935023
    - name: scaling_speed
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.31177421746048395
    - name: sim_granularity
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.02537100021859829
    - name: stop_time_buffer
      ns: move_base/DWAPlannerROS
      type: double
      value: 1.0
    - name: oscillation_reset_dist
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.054441156382406555
  in_row:
    edges:
    - WayPoint0_WayPoint1
    - WayPoint0_WayPoint40
    - WayPoint1_WayPoint0
    - WayPoint1_WayPoint2
    - WayPoint10_WayPoint11
    - WayPoint10_WayPoint41
    - WayPoint11_WayPoint10
    - WayPoint11_WayPoint12
    - WayPoint12_WayPoint11
    - WayPoint12_WayPoint13
    - WayPoint13_WayPoint12
    - WayPoint13_WayPoint14
    - WayPoint14_WayPoint13
    - WayPoint14_WayPoint15
    - WayPoint15_WayPoint14
    - WayPoint15_WayPoint16
    - WayPoint16_WayPoint15
    - WayPoint16_WayPoint17
    - WayPoint17_WayPoint16
    - WayPoint17_WayPoint18
    - WayPoint18_WayPoint17
    - WayPoint18_WayPoint19
    - WayPoint19_WayPoint18
    - WayPoint19_WayPoint45
    - WayPoint2_WayPoint1
    - WayPoint2_WayPoint3
    - WayPoint20_WayPoint21
    - WayPoint20_WayPoint42
    - WayPoint21_WayPoint20
    - WayPoint21_WayPoint22
    - WayPoint22_WayPoint21
    - WayPoint22_WayPoint23
    - WayPoint23_WayPoint22
    - WayPoint23_WayPoint24
    - WayPoint24_WayPoint23
    - WayPoint24_WayPoint25
    - WayPoint25_WayPoint24
    - WayPoint25_WayPoint26
    - WayPoint26_WayPoint25
    - WayPoint26_WayPoint27
    - WayPoint27_WayPoint26
    - WayPoint27_WayPoint28
    - WayPoint28_WayPoint27
    - WayPoint28_WayPoint29
    - WayPoint29_WayPoint28
    - WayPoint29_WayPoint46
    - WayPoint3_WayPoint2
    - WayPoint3_WayPoint4
    - WayPoint30_WayPoint31
    - WayPoint30_WayPoint43
    - WayPoint31_WayPoint30
    - WayPoint31_WayPoint32
    - WayPoint32_WayPoint31
    - WayPoint32_WayPoint33
    - WayPoint33_WayPoint32
    - WayPoint33_WayPoint34
    - WayPoint34_WayPoint33
    - WayPoint34_WayPoint35
    - WayPoint35_WayPoint34
    - WayPoint35_WayPoint36
    - WayPoint36_WayPoint35
    - WayPoint36_WayPoint37
    - WayPoint37_WayPoint36
    - WayPoint37_WayPoint38
    - WayPoint38_WayPoint37
    - WayPoint38_WayPoint39
    - WayPoint39_WayPoint38
    - WayPoint39_WayPoint47
    - WayPoint4_WayPoint3
    - WayPoint4_WayPoint5
    - WayPoint5_WayPoint4
    - WayPoint5_WayPoint6
    - WayPoint6_WayPoint5
    - WayPoint6_WayPoint7
    - WayPoint7_WayPoint6
    - WayPoint7_WayPoint8
    - WayPoint8_WayPoint7
    - WayPoint8_WayPoint9
    - WayPoint9_WayPoint8
    - WayPoint9_WayPoint44
    parameters:
    - name: forward_point_distance
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.48297542551971
    - name: vth_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 67.0
    - name: prune_plan
      ns: move_base/DWAPlannerROS
      type: bool
      value: true
    - name: goal_distance_bias
      ns: move_base/DWAPlannerROS
      type: int
      value: 37.0
    - name: occdist_scale
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.17095456476021975
    - name: vx_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 35.0
    - name: path_distance_bias
      ns: move_base/DWAPlannerROS
      type: int
      value: 28.786107042177363
    - name: sim_time
      ns: move_base/DWAPlannerROS
      type: double
      value: 2.56592652856906
    - name: max_scaling_factor
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.572649261744206
    - name: scaling_speed
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.013910991085600694
    - name: sim_granularity
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.04403610426260697
    - name: stop_time_buffer
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.18229162576485147
    - name: oscillation_reset_dist
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.015779064792816565
  out_row:
    edges:
    - WayPoint48_WayPoint40
    - WayPoint48_WayPoint41
    - WayPoint48_WayPoint42
    - WayPoint48_WayPoint43
    - WayPoint40_WayPoint48
    - WayPoint41_WayPoint48
    - WayPoint42_WayPoint48
    - WayPoint43_WayPoint48
    - WayPoint49_WayPoint40
    - WayPoint49_WayPoint41
    - WayPoint49_WayPoint42
    - WayPoint49_WayPoint43
    - WayPoint40_WayPoint49
    - WayPoint41_WayPoint49
    - WayPoint42_WayPoint49
    - WayPoint43_WayPoint49
    - WayPoint50_WayPoint44
    - WayPoint50_WayPoint45
    - WayPoint50_WayPoint46
    - WayPoint50_WayPoint47
    - WayPoint44_WayPoint50
    - WayPoint45_WayPoint50
    - WayPoint46_WayPoint50
    - WayPoint47_WayPoint50
    - WayPoint51_WayPoint44
    - WayPoint51_WayPoint45
    - WayPoint51_WayPoint46
    - WayPoint51_WayPoint47
    - WayPoint44_WayPoint51
    - WayPoint45_WayPoint51
    - WayPoint46_WayPoint51
    - WayPoint47_WayPoint51
    - WayPoint54_WayPoint48
    - WayPoint48_WayPoint54
    - WayPoint48_WayPoint49
    - WayPoint49_WayPoint48
    - WayPoint49_WayPoint53
    - WayPoint53_WayPoint49
    - WayPoint49_WayPoint52
    - WayPoint52_WayPoint49
    - WayPoint50_WayPoint51
    - WayPoint51_WayPoint50
    - WayPoint53_WayPoint52
    - WayPoint52_WayPoint53
    parameters: *id001
