edge_nav_reconfig_groups:
  irn:
    edges:
    - WayPoint1_WayPoint2
    - WayPoint1_WayPoint5
    - WayPoint10_WayPoint11
    - WayPoint100_WayPoint101
    - WayPoint100_WayPoint99
    - WayPoint101_WayPoint100
    - WayPoint102_WayPoint103
    - WayPoint102_WayPoint133
    - WayPoint103_WayPoint102
    - WayPoint103_WayPoint104
    - WayPoint104_WayPoint103
    - WayPoint104_WayPoint105
    - WayPoint105_WayPoint104
    - WayPoint105_WayPoint106
    - WayPoint106_WayPoint105
    - WayPoint106_WayPoint107
    - WayPoint107_WayPoint106
    - WayPoint107_WayPoint108
    - WayPoint108_WayPoint107
    - WayPoint108_WayPoint109
    - WayPoint109_WayPoint108
    - WayPoint109_WayPoint110
    - WayPoint11_WayPoint10
    - WayPoint11_WayPoint12
    - WayPoint110_WayPoint109
    - WayPoint111_WayPoint112
    - WayPoint111_WayPoint132
    - WayPoint112_WayPoint111
    - WayPoint112_WayPoint113
    - WayPoint113_WayPoint112
    - WayPoint113_WayPoint114
    - WayPoint114_WayPoint113
    - WayPoint114_WayPoint115
    - WayPoint115_WayPoint114
    - WayPoint115_WayPoint116
    - WayPoint116_WayPoint115
    - WayPoint116_WayPoint117
    - WayPoint117_WayPoint116
    - WayPoint117_WayPoint118
    - WayPoint118_WayPoint117
    - WayPoint118_WayPoint119
    - WayPoint119_WayPoint118
    - WayPoint12_WayPoint11
    - WayPoint12_WayPoint13
    - WayPoint120_WayPoint121
    - WayPoint121_WayPoint120
    - WayPoint121_WayPoint122
    - WayPoint122_WayPoint121
    - WayPoint122_WayPoint123
    - WayPoint123_WayPoint122
    - WayPoint123_WayPoint124
    - WayPoint124_WayPoint123
    - WayPoint124_WayPoint125
    - WayPoint125_WayPoint124
    - WayPoint125_WayPoint126
    - WayPoint126_WayPoint125
    - WayPoint126_WayPoint127
    - WayPoint127_WayPoint126
    - WayPoint127_WayPoint128
    - WayPoint128_WayPoint127
    - WayPoint128_WayPoint131
    - WayPoint13_WayPoint12
    - WayPoint13_WayPoint14
    - WayPoint131_WayPoint128
    - WayPoint132_WayPoint111
    - WayPoint133_WayPoint102
    - WayPoint134_WayPoint93
    - WayPoint138_WayPoint92
    - WayPoint139_WayPoint80
    - WayPoint14_WayPoint13
    - WayPoint14_WayPoint15
    - WayPoint15_WayPoint14
    - WayPoint15_WayPoint16
    - WayPoint16_WayPoint15
    - WayPoint16_WayPoint17
    - WayPoint17_WayPoint16
    - WayPoint17_WayPoint18
    - WayPoint18_WayPoint17
    - WayPoint18_WayPoint64
    - WayPoint19_WayPoint20
    - WayPoint19_WayPoint60
    - WayPoint2_WayPoint1
    - WayPoint2_WayPoint6
    - WayPoint20_WayPoint19
    - WayPoint20_WayPoint21
    - WayPoint21_WayPoint20
    - WayPoint21_WayPoint22
    - WayPoint22_WayPoint21
    - WayPoint22_WayPoint23
    - WayPoint23_WayPoint22
    - WayPoint23_WayPoint24
    - WayPoint24_WayPoint23
    - WayPoint24_WayPoint25
    - WayPoint25_WayPoint24
    - WayPoint25_WayPoint26
    - WayPoint26_WayPoint25
    - WayPoint26_WayPoint27
    - WayPoint27_WayPoint26
    - WayPoint28_WayPoint29
    - WayPoint28_WayPoint59
    - WayPoint29_WayPoint28
    - WayPoint29_WayPoint30
    - WayPoint3_WayPoint4
    - WayPoint3_WayPoint7
    - WayPoint30_WayPoint29
    - WayPoint30_WayPoint31
    - WayPoint31_WayPoint30
    - WayPoint31_WayPoint32
    - WayPoint32_WayPoint31
    - WayPoint32_WayPoint33
    - WayPoint33_WayPoint32
    - WayPoint33_WayPoint34
    - WayPoint34_WayPoint33
    - WayPoint34_WayPoint35
    - WayPoint35_WayPoint34
    - WayPoint35_WayPoint36
    - WayPoint36_WayPoint35
    - WayPoint37_WayPoint38
    - WayPoint37_WayPoint58
    - WayPoint38_WayPoint37
    - WayPoint38_WayPoint39
    - WayPoint39_WayPoint38
    - WayPoint39_WayPoint40
    - WayPoint4_WayPoint3
    - WayPoint4_WayPoint5
    - WayPoint40_WayPoint39
    - WayPoint40_WayPoint41
    - WayPoint41_WayPoint40
    - WayPoint41_WayPoint42
    - WayPoint42_WayPoint41
    - WayPoint42_WayPoint43
    - WayPoint43_WayPoint42
    - WayPoint43_WayPoint44
    - WayPoint44_WayPoint43
    - WayPoint44_WayPoint45
    - WayPoint45_WayPoint44
    - WayPoint46_WayPoint47
    - WayPoint47_WayPoint46
    - WayPoint47_WayPoint48
    - WayPoint48_WayPoint47
    - WayPoint48_WayPoint49
    - WayPoint49_WayPoint48
    - WayPoint49_WayPoint50
    - WayPoint5_WayPoint1
    - WayPoint5_WayPoint4
    - WayPoint50_WayPoint49
    - WayPoint50_WayPoint51
    - WayPoint51_WayPoint50
    - WayPoint51_WayPoint52
    - WayPoint52_WayPoint51
    - WayPoint52_WayPoint53
    - WayPoint53_WayPoint52
    - WayPoint53_WayPoint54
    - WayPoint54_WayPoint53
    - WayPoint54_WayPoint57
    - WayPoint56_WayPoint63
    - WayPoint56_WayPoint66
    - WayPoint57_WayPoint54
    - WayPoint58_WayPoint37
    - WayPoint59_WayPoint28
    - WayPoint6_WayPoint2
    - WayPoint6_WayPoint65
    - WayPoint60_WayPoint19
    - WayPoint63_WayPoint56
    - WayPoint64_WayPoint18
    - WayPoint65_WayPoint6
    - WayPoint66_WayPoint56
    - WayPoint66_WayPoint74
    - WayPoint7_WayPoint3
    - WayPoint7_WayPoint8
    - WayPoint74_WayPoint66
    - WayPoint75_WayPoint76
    - WayPoint75_WayPoint79
    - WayPoint76_WayPoint75
    - WayPoint76_WayPoint80
    - WayPoint77_WayPoint78
    - WayPoint77_WayPoint81
    - WayPoint78_WayPoint77
    - WayPoint78_WayPoint79
    - WayPoint79_WayPoint75
    - WayPoint79_WayPoint78
    - WayPoint8_WayPoint7
    - WayPoint8_WayPoint9
    - WayPoint80_WayPoint139
    - WayPoint80_WayPoint76
    - WayPoint81_WayPoint77
    - WayPoint81_WayPoint82
    - WayPoint82_WayPoint81
    - WayPoint82_WayPoint83
    - WayPoint83_WayPoint82
    - WayPoint84_WayPoint85
    - WayPoint85_WayPoint84
    - WayPoint85_WayPoint86
    - WayPoint86_WayPoint85
    - WayPoint86_WayPoint87
    - WayPoint87_WayPoint86
    - WayPoint87_WayPoint88
    - WayPoint88_WayPoint87
    - WayPoint88_WayPoint89
    - WayPoint89_WayPoint88
    - WayPoint89_WayPoint90
    - WayPoint9_WayPoint8
    - WayPoint90_WayPoint91
    - WayPoint90_WayPoint89
    - WayPoint91_WayPoint92
    - WayPoint91_WayPoint90
    - WayPoint92_WayPoint138
    - WayPoint92_WayPoint91
    - WayPoint93_WayPoint94
    - WayPoint93_WayPoint134
    - WayPoint94_WayPoint95
    - WayPoint94_WayPoint93
    - WayPoint95_WayPoint96
    - WayPoint95_WayPoint94
    - WayPoint96_WayPoint97
    - WayPoint96_WayPoint95
    - WayPoint97_WayPoint98
    - WayPoint97_WayPoint96
    - WayPoint98_WayPoint99
    - WayPoint98_WayPoint97
    - WayPoint99_WayPoint100
    - WayPoint99_WayPoint98
    parameters:
    - &id001
      name: vth_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 67.0
    - &id002
      name: goal_distance_bias
      ns: move_base/DWAPlannerROS
      type: double
      value: 37.0
    - &id003
      name: path_distance_bias
      ns: move_base/DWAPlannerROS
      type: double
      value: 28.7861070422
    - &id004
      name: min_vel_y
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.0
    - &id005
      name: forward_point_distance
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.48297542552
    - &id006
      name: max_vel_y
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.0
    - &id007
      name: prune_plan
      ns: move_base/DWAPlannerROS
      type: bool
      value: true
    - &id008
      name: occdist_scale
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.17095456476
    - &id009
      name: vx_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 35.0
    - &id010
      name: sim_time
      ns: move_base/DWAPlannerROS
      type: double
      value: 2.56592652857
    - &id011
      name: max_scaling_factor
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.572649261744
    - &id012
      name: scaling_speed
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.0139109910856
    - &id013
      name: vy_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 1
    - &id014
      name: sim_granularity
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.0440361042626
    - &id015
      name: stop_time_buffer
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.182291625765
    - &id016
      name: oscillation_reset_dist
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.0157790647928
  orn:
    edges:
    - WayPoint66_WayPoint57
    - WayPoint66_WayPoint58
    - WayPoint66_WayPoint59
    - WayPoint66_WayPoint60
    - WayPoint66_WayPoint64
    - WayPoint66_WayPoint65
    - WayPoint56_WayPoint57
    - WayPoint56_WayPoint58
    - WayPoint56_WayPoint59
    - WayPoint56_WayPoint60
    - WayPoint56_WayPoint64
    - WayPoint56_WayPoint65
    - WayPoint63_WayPoint57
    - WayPoint63_WayPoint58
    - WayPoint63_WayPoint59
    - WayPoint63_WayPoint60
    - WayPoint63_WayPoint64
    - WayPoint63_WayPoint65
    - WayPoint67_WayPoint131
    - WayPoint67_WayPoint132
    - WayPoint67_WayPoint133
    - WayPoint67_WayPoint134
    - WayPoint67_WayPoint138
    - WayPoint67_WayPoint139
    - WayPoint73_WayPoint131
    - WayPoint73_WayPoint132
    - WayPoint73_WayPoint133
    - WayPoint73_WayPoint134
    - WayPoint73_WayPoint138
    - WayPoint73_WayPoint139
    - WayPoint73_WayPoint141
    - WayPoint74_WayPoint131
    - WayPoint74_WayPoint132
    - WayPoint74_WayPoint133
    - WayPoint74_WayPoint134
    - WayPoint74_WayPoint138
    - WayPoint74_WayPoint139
    - WayPoint74_WayPoint140
    - WayPoint70_WayPoint69
    - WayPoint71_WayPoint69
    - WayPoint72_WayPoint69
    - WayPoint69_WayPoint68
    - WayPoint68_WayPoint67
    - WayPoint67_WayPoint73
    - WayPoint73_WayPoint74
    - WayPoint57_WayPoint66
    - WayPoint58_WayPoint66
    - WayPoint59_WayPoint66
    - WayPoint60_WayPoint66
    - WayPoint64_WayPoint66
    - WayPoint65_WayPoint66
    - WayPoint57_WayPoint56
    - WayPoint58_WayPoint56
    - WayPoint59_WayPoint56
    - WayPoint60_WayPoint56
    - WayPoint64_WayPoint56
    - WayPoint65_WayPoint56
    - WayPoint57_WayPoint63
    - WayPoint58_WayPoint63
    - WayPoint59_WayPoint63
    - WayPoint60_WayPoint63
    - WayPoint64_WayPoint63
    - WayPoint65_WayPoint63
    - WayPoint131_WayPoint67
    - WayPoint132_WayPoint67
    - WayPoint133_WayPoint67
    - WayPoint134_WayPoint67
    - WayPoint138_WayPoint67
    - WayPoint139_WayPoint67
    - WayPoint131_WayPoint73
    - WayPoint132_WayPoint73
    - WayPoint133_WayPoint73
    - WayPoint134_WayPoint73
    - WayPoint138_WayPoint73
    - WayPoint139_WayPoint73
    - WayPoint131_WayPoint74
    - WayPoint132_WayPoint74
    - WayPoint133_WayPoint74
    - WayPoint134_WayPoint74
    - WayPoint138_WayPoint74
    - WayPoint139_WayPoint74
    - WayPoint140_WayPoint74
    - WayPoint141_WayPoint73
    - WayPoint69_WayPoint70
    - WayPoint69_WayPoint71
    - WayPoint69_WayPoint72
    - WayPoint68_WayPoint69
    - WayPoint67_WayPoint68
    - WayPoint73_WayPoint67
    - WayPoint74_WayPoint73
    parameters:
    - *id001
    - *id002
    - *id003
    - *id004
    - *id005
    - *id006
    - *id007
    - *id008
    - *id009
    - *id010
    - *id011
    - *id012
    - *id013
    - *id014
    - *id015
    - *id016
  utn:
    edges:
    - WayPoint46_WayPoint45
    - WayPoint45_WayPoint46
    - WayPoint45_WayPoint36
    - WayPoint36_WayPoint45
    - WayPoint36_WayPoint27
    - WayPoint27_WayPoint36
    - WayPoint27_WayPoint10
    - WayPoint10_WayPoint27
    - WayPoint10_WayPoint9
    - WayPoint9_WayPoint10
    - WayPoint120_WayPoint119
    - WayPoint119_WayPoint120
    - WayPoint119_WayPoint110
    - WayPoint110_WayPoint119
    - WayPoint110_WayPoint101
    - WayPoint101_WayPoint110
    - WayPoint101_WayPoint84
    - WayPoint84_WayPoint101
    - WayPoint84_WayPoint83
    - WayPoint83_WayPoint84
    parameters:
    - name: vth_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 8.0
    - name: goal_distance_bias
      ns: move_base/DWAPlannerROS
      type: int
      value: 29.0
    - name: path_distance_bias
      ns: move_base/DWAPlannerROS
      type: int
      value: 41.0
    - name: min_vel_y
      ns: move_base/DWAPlannerROS
      type: double
      value: -0.35
    - name: forward_point_distance
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.05
    - name: max_vel_y
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.35
    - name: prune_plan
      ns: move_base/DWAPlannerROS
      type: bool
      value: false
    - name: occdist_scale
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.354307473006
    - name: vx_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 1.0
    - name: sim_time
      ns: move_base/DWAPlannerROS
      type: double
      value: 3.33906319807
    - name: max_scaling_factor
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.283085202888
    - name: scaling_speed
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.302724798452
    - name: vy_samples
      ns: move_base/DWAPlannerROS
      type: int
      value: 49.0
    - name: sim_granularity
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.216821592816
    - name: stop_time_buffer
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.789168747746
    - name: oscillation_reset_dist
      ns: move_base/DWAPlannerROS
      type: double
      value: 0.033945588782

