topological_map_manager:
  multi_robot_mode: true
  presence_topics:
    - thorvald_001/current_node
    - thorvald_002/current_node
    - thorvald_008/current_node
    - thorvald_010/current_node
    - thorvald_014/current_node
    - thorvald_015/current_node
    - picker01/current_node
    - picker02/current_node
    - picker03/current_node
    - picker04/current_node
    - picker05/current_node
    - picker06/current_node
    - picker07/current_node
    - picker08/current_node
    - picker101/current_node
    - picker102/current_node
    - picker103/current_node
  presence_agents:
    - thorvald_001
    - thorvald_002
    - thorvald_008
    - thorvald_010
    - thorvald_014
    - thorvald_015
    - picker01
    - picker02
    - picker03
    - picker04
    - picker05
    - picker06
    - picker07
    - picker08
    - picker101
    - picker102
    - picker103
