des_env: ros # simpy or ros
n_farm_rows: 5 # number of rows in the farm / poly-tunnel
half_rows: false # whether the first and last rows are half (berries only on one side) or full rows (berries on both sides)
head_row_node_dist: [5.0] # distance from head node to the first row node of each row
head_node_y: [1.0] # y coordinate of head nodes
row_node_dist: [2.0] # distance between two nodes in each row, m
row_length: [10.0] # length of rows, m
row_spacing: [2] # spacing between two rows in the farm, m
n_pickers: 3 # number of pickers
picking_rate: [0.2] # speed of pickers while picking, m/s
picker_transportation_rate: [0.8] # transportation speed of pickers, m/s
picker_max_n_trays: [1] # maximum number of trays that can be carried by each pickers
picker_unloading_time: [10.0] # time required by each picker to unload a tray at local storage / robot, s
tray_capacity: 3000 # capacity of each tray, g 
yield_per_node: [200.0] # yield at a topo_nav node (from the node to the next), per row, g
n_local_storages: 1 # number of local storage stations
n_robots: 0 # number of robots in the farm
robot_transportation_rate: [2.0] # speed of a robot, m/s
robot_max_n_trays: [4] # maximum number of trays that can be carried by the robot
robot_unloading_time: [10] # time required by the robot to unload a tray at local storage, s

