export TMAP="riseholme_bidirectional"
export MAP="`readlink -f ../../rasberry_navigation/maps/riseholme.yaml`"
export NOGOMAP="`readlink -f ../../rasberry_navigation/maps/riseholme_no_go.yaml`"
export ROSBRIDGE_IP="10.8.0.18"
#export ROSBRIDGE_IP="localhost"
