export TMAP="riseholme_sim"
export MAP="`readlink -f ../../rasberry_navigation/maps/riseholme_sim.yaml`"
export NOGOMAP="`readlink -f ../../rasberry_navigation/maps/riseholme_sim_no_go.yaml`"
export ROSBRIDGE_IP="10.8.0.18"
export USE_SIM=true
export GAZEBO_WORLD=riseholme
export EKF_PUBLISH_TF=false
export USE_IMU=false
export USE_CARROT=false
