robots:
  lindsey:
    description: "Lindsey"
    ip: "10.8.0.22"
    ns: ""
    motors: 2 
    topics: 
      scan_front: "/scan_front"
      scan_back: "/scan_back"
      motor_control: "/motor_controller_data"
      imu: "/imu/data"
      gps: "/gps/fix"
      battery: "/battery_data"
      ouster: "/ouster/cloud"
  thorvald-008:
    description: "UOL robot 008"
    ip: "10.8.0.31"
    ns: "" 
    motors: 4 
    topics: 
      scan_front: "/scan_front"
      scan_back: "/scan_back"
      motor_control: "/motor_controller_data"
      imu: "/imu/data"
      gps: "/gps/fix"
      battery: "/battery_data"
      ouster: "/ouster/cloud"
  thorvald-014:
    description: "UOL robot 014"
    ip: "10.8.0.33"
    ns: "" 
    motors: 4 
    topics: 
      scan_front: "/scan_front"
      scan_back: "/scan_back"
      motor_control: "/motor_controller_data"
      imu: "/imu/data"
      gps: "/gps/fix"
      battery: "/battery_data"
      ouster: "/ouster/cloud"
  dummy:
    description: "localhost for debugging"
    ip: "127.0.0.1"
    ns: ""
    motors: 2 
    topics: 
      scan_front: "/scan_front"
      scan_back: "/scan_back"
      motor_control: "/motor_controller_data"
      imu: "/imu/data"
      gps: "/gps/fix"
      battery: "/battery_data"
      ouster: "/ouster/cloud"
