/move_base/DWAPlannerROS: 
  path_distance_bias: 
    include: 1 
    type: "float"
    min: 1.0
    max: 100.0
  goal_distance_bias: 
    include: 1 
    type: "float"
    min: 1.0
    max: 100.0
  occdist_scale: 
    include: 0 
    type: "float"
    min: 1.0
    max: 100.0
  prune_plan:
    include: 0 
    type: "bool"

/move_base/global_costmap/global_inflation_layer:
  cost_scaling_factor: 
    include: 0 
    type: "float"
    min: 1.0
    max: 100.0
  inflation_radius: 
    include: 0 
    type: "float"
    min: 1.0
    max: 100.0

/move_base/local_costmap/local_inflation_layer:
  cost_scaling_factor: 
    include: 0 
    type: "float"
    min: 1.0
    max: 100.0
  inflation_radius: 
    include: 0 
    type: "float"
    min: 1.0
    max: 100.0

