# REGISTER YOUR PARAMETERS FOR OPTMISATION HERE.
# You must specify the name space (ns) of your parameters (as below).
# type: parameter type - can be double, integer (int) or boolean (bool).
# min: minimum value of parameter considered by the genetic algorithm (does not apply to type bool).
# max: maximum value of parameter considered by the genetic algorithm (does not apply to type bool).


- name: dt_ref    # dt_hysteresis constrained to be 10% of dt_ref as recommended here http://wiki.ros.org/teb_local_planner
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.02
  max: 1.0

- name: global_plan_overwrite_orientation    
  ns: move_base/TebLocalPlannerROS
  type: bool
  min: nan
  max: nan

- name: global_plan_viapoint_sep  
  ns: move_base/TebLocalPlannerROS
  type: double
  min: -0.1
  max: 1.0

- name: max_global_plan_lookahead_dist  
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 1.0
  max: 5.0

- name: max_number_classes 
  ns: move_base/TebLocalPlannerROS
  type: int
  min: 1
  max: 10

- name: min_obstacle_dist
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.1
  max: 0.5

- name: no_inner_iterations
  ns: move_base/TebLocalPlannerROS
  type: int
  min: 2
  max: 10

- name: no_outer_iterations
  ns: move_base/TebLocalPlannerROS
  type: int
  min: 2
  max: 10

- name: penalty_epsilon    # should be < min(max_vel_x, max_vel_x_backwards, max_vel_theta, acc_lim_x). Default = 0.1, min possible = 0.0, max possible = 1.0
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.01
  max: 0.19

- name: weight_acc_lim_theta
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.5
  max: 5.0

- name: weight_acc_lim_x
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.5
  max: 5.0

- name: weight_max_vel_theta
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.5
  max: 10.0

- name: weight_max_vel_x
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.5
  max: 10.0

- name: weight_obstacle
  ns: move_base/TebLocalPlannerROS
  type: int
  min: 10
  max: 100

- name: weight_optimaltime
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.2
  max: 5.0

- name: weight_viapoint
  ns: move_base/TebLocalPlannerROS
  type: double
  min: 0.1
  max: 2.0

