# REGISTER YOUR PARAMETERS FOR OPTMISATION HERE.
# You must specify the name space (ns) of your parameters (as below).
# type: parameter type - can be double, integer (int) or boolean (bool).
# min: minimum value of parameter considered by the genetic algorithm (does not apply to type bool).
# max: maximum value of parameter considered by the genetic algorithm (does not apply to type bool).

- name: min_particles
  ns: amcl
  type: int
  min: 20
  max: 500

- name: max_particles
  ns: amcl
  type: int
  min: 1000
  max: 10000

- name: update_min_d
  ns: amcl
  type: double
  min: 0.05
  max: 0.5

- name: update_min_a
  ns: amcl
  type: double
  min: 0.26
  max: 0.78

- name: laser_max_beams
  ns: amcl
  type: int
  min: 10
  max: 50

- name: laser_sigma_hit
  ns: amcl
  type: double
  min: 0.05
  max: 0.5

- name: laser_lambda_short
  ns: amcl
  type: double
  min: 0.02
  max: 0.2

- name: laser_likelihood_max_dist
  ns: amcl
  type: double
  min: 0.5
  max: 2.5

