# CONFIGURATION FOR THE SCENARIO SERVER
start_node: WayPoint59
goal_node: WayPoint35
robot_name: thorvald_ii
max_wait_time: 210 # time (seconds) allowed to complete scenario.
coords_file: pole_coords.json # optional - the GA will try to minimise the squared Euclidean distance between the robot and the coordinates in this file.

# Note on coords_file: should be located in `/rasberry_optimise/resources`
