# CONFIGURATION FOR THE SCENARIO SERVER
robot_name: thorvald_ii
start_node: WayPoint35
goal_nodes: [WayPoint44, WayPoint35]
max_wait_times: [90, 90] # time (seconds) allowed to complete each goal.
centres: centres_row3_sim.json # optional - the GA will try to minimise distance to centre path

# Note on centres file: should be located in `/rasberry_optimise/resources`
