# CONFIGURATION FOR THE SCENARIO SERVER
start_node: WayPoint35
goal_node: WayPoint44
robot_name: thorvald_ii
max_wait_time: 90 # time (seconds) allowed to complete scenario.
centres: centres_row3_sim.json # optional - the GA will try to minimise distance to centre path

# Note on centres file: should be located in `/rasberry_optimise/resources`
