# CONFIGURATION FOR THE SCENARIO SERVER
robot_name: thorvald_ii
start_node: WayPoint27
start_orientation: 3.14 # (radians). Optional - defaults to orientation of the start node
goal_nodes: [WayPoint9, WayPoint46]
max_wait_times: [45, 90] # time (seconds) allowed to complete each goal.
path: centres_row3_sim.yaml # optional - the deviation of the robot's trajectory from this path is reported by the scenario server as the `path error`.

# Note on path file: should be located in `/rasberry_optimise/resources`
