global_frame: /map
robot_base_frame: /base_link

#footprint: [[0.785, 0.60], [0.785, -0.60], [-0.785, -0.60], [-0.785, 0.60]]
#footprint: [[0.67, 0.385], [0.67, -0.385], [-0.67, -0.385], [-0.67, 0.385]]
footprint: [[0.76, 0.50], [0.76, -0.50], [-0.76, -0.50], [-0.76, 0.50]]

map_layer:
  map_topic: /map

no_go_layer:
  map_topic: /no_go_map

global_inflation_layer:
  inflation_radius: 0.66
  cost_scaling_factor: 0.97

local_inflation_layer:
  inflation_radius: 0.66
  cost_scaling_factor: 0.97

obstacle_layer:
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  raytrace_range: 3.0

  unknown_threshold: 6
  mark_threshold: 0
  
  track_unknown_space: true
  
  observation_sources: front_laser_scan_sensor back_laser_scan_sensor
#  observation_sources: fl_laser_scan_sensor
  front_laser_scan_sensor: {sensor_frame: hokuyo_front, data_type: LaserScan, topic: /scan_front, marking: true, clearing: true}
  back_laser_scan_sensor: {sensor_frame: hokuyo_back, data_type: LaserScan, topic: /scan_back, marking: true, clearing: true}

global_obstacle_layer:
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  raytrace_range: 3.0

  unknown_threshold: 6
  mark_threshold: 0

  track_unknown_space: true

  observation_sources: front_laser_scan_sensor back_laser_scan_sensor
#  observation_sources: fl_laser_scan_sensor
  front_laser_scan_sensor: {sensor_frame: hokuyo_front, data_type: LaserScan, topic: /scan_front, marking: false, clearing: false}
  back_laser_scan_sensor: {sensor_frame: hokuyo_back, data_type: LaserScan, topic: /scan_back, marking: false, clearing: false}
#marking and clearing set to true for norway_poles_demo purposes

